#!/usr/bin/env python3
"""
Team Name Cleaning Script
Auto-generated by csv_analyzer.py

This script applies team name standardization across all CSV files.
"""

import pandas as pd
import os
import glob
from datetime import datetime

def clean_team_names():
    """Apply team name cleaning to all CSV files"""
    
    # Team name mapping dictionary
    team_name_mapping = {
        # SLASH fixes
        'Bodo/Glimt': 'Bodo Glimt',
        'Ull/Kisa': 'Ull Kisa',

        # SPACE_NUMBER fixes
        'Sarpsborg 08': 'Sarpsborg08',

        # HYPHEN fixes
        'Ham-Kam': 'Ham Kam',
        'Oud-Heverlee Leuven': 'Oud Heverlee Leuven',

        # DOT fixes
        'Ad. Demirspor': 'Ad Demirspor',
        'St. Gallen': 'St Gallen',
        'St. Gilloise': 'St Gilloise',

        # APOSTROPHE fixes
        "M'gladbach": 'Mgladbach',
        "Nott'm Forest": 'Nottm Forest',

    }
    
    csv_files = glob.glob("csvs/*.csv")
    changes_made = {}
    
    print(f"🧹 Starting team name cleaning for {len(csv_files)} files...")
    
    for csv_file in csv_files:
        filename = os.path.basename(csv_file)
        file_changes = 0
        
        try:
            # Try different encodings
            for encoding in ['utf-8', 'latin-1', 'cp1252']:
                try:
                    df = pd.read_csv(csv_file, encoding=encoding)
                    break
                except UnicodeDecodeError:
                    continue
            else:
                print(f"❌ Could not read {filename}")
                continue
            
            # Find team columns
            team_columns = []
            for col in df.columns:
                if any(keyword in col.lower() for keyword in ['home', 'away', 'team']):
                    team_columns.append(col)
            
            if not team_columns:
                continue
            
            # Apply cleaning to team columns
            for col in team_columns:
                for original, cleaned in team_name_mapping.items():
                    mask = df[col] == original
                    if mask.any():
                        df.loc[mask, col] = cleaned
                        count = mask.sum()
                        file_changes += count
                        print(f"  📝 {filename}: {col} '{original}' → '{cleaned}' ({count} occurrences)")
            
            # Save cleaned file if changes were made
            if file_changes > 0:
                # Create backup
                backup_file = csv_file + f".backup_{datetime.now().strftime('%Y%m%d_%H%M%S')}"
                df_original = pd.read_csv(csv_file)
                df_original.to_csv(backup_file, index=False)
                
                # Save cleaned version
                df.to_csv(csv_file, index=False)
                changes_made[filename] = file_changes
                print(f"  ✅ {filename}: {file_changes} changes applied (backup created)")
        
        except Exception as e:
            print(f"❌ Error processing {filename}: {e}")
    
    print(f"\n🎉 Cleaning complete!")
    print(f"📊 Files modified: {len(changes_made)}")
    print(f"📊 Total changes: {sum(changes_made.values())}")
    
    if changes_made:
        print("\n📋 Summary of changes:")
        for filename, count in changes_made.items():
            print(f"  • {filename}: {count} changes")

if __name__ == "__main__":
    clean_team_names()
